name: Build TWRP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y python3
          sudo apt-get install -y bc
          sudo apt-get install -y openjdk-11-jdk

      - name: Initialize Repo
        run: |
          mkdir ~/twrp
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0-deprecated
          repo sync -j$(nproc)

      - name: Copy Device Tree
        run: |
          mkdir -p ~/twrp/device/nothing/Spacewar
          cp -r device/nothing/Spacewar ~/twrp/device/nothing/Spacewar

      - name: Set up TWRP Build Environment
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch omni_Spacewar-eng

      - name: Modify BoardConfig.mk
        run: |
          echo "TW_THEME := portrait_hdpi" >> ~/twrp/device/nothing/Spacewar/BoardConfig.mk
          echo "RECOVERY_SDCARD_ON_DATA := true" >> ~/twrp/device/nothing/Spacewar/BoardConfig.mk
          echo "BOARD_HAS_NO_REAL_SDCARD := true" >> ~/twrp/device/nothing/Spacewar/BoardConfig.mk

      - name: Copy twrp.fstab (if needed)
        run: |
          if [ -f "device/nothing/Spacewar/twrp.fstab" ]; then
            mkdir -p ~/twrp/recovery/root/etc
            cp device/nothing/Spacewar/twrp.fstab ~/twrp/recovery/root/etc/twrp.fstab
            echo "PRODUCT_COPY_FILES += device/nothing/Spacewar/twrp.fstab:recovery/root/etc/twrp.fstab" >> ~/twrp/device/nothing/Spacewar/device.mk
          fi

      - name: Build TWRP
        run: |
          cd ~/twrp
          make clean && make -j$(nproc) recoveryimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: twrp-recovery
          path: ~/twrp/out/target/product/Spacewar/recovery.img

