name: Build TWRP Image for Nothing Phone 1 Spacewar

on:
  workflow_dispatch:
    inputs:
      TWRP_VERSION:
        description: 'TWRP Version to Build.'
        required: true
        default: '14'
        type: options
          - twrp-14
          - twrp-12.1
          - twrp-11
jobs:
  build:
    name: Build TWRP for Spacewar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Building Dependencies
        run: |
          sudo apt update
          sudo apt install cpio python3 pip
          
      - name: Install Repo
        run: |
          mkdir -p ~/.bin
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo
      - name: Clone TWRP Source
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b ${{ inputs.TWRP_VERSION }}
          repo sync -j$(nproc)
      - name: Clone TWRP Device Tree
        run: |
          cd twrp_source
          mkdir -p device/nothing/Spacewar
          git clone https://github.com/Gamer09CF/recovery_device_nothing_Spacewar.git device/nothing/Spacewar/
      - name: Initialize Build
        run: |
          source build/envsetup.sh
          lunch twrp_Spacewar-eng
      - name: Start Build
        run: |
          cd android
          make clean
          make recoveryimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-image-Spacewar-${{ github.run_id }}
          path: twrp_source/android/out/target/product/Spacewar/recovery.img

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: android/out/target/product/Spacewar/recovery.img
          name: TWRP for Spacewar - Build ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Unofficial TWRP build for Spacewar
            Device Tree: https://github.com/Gamer09CF/recovery_device_nothing_Spacewar/tree/master
