name: Build TWRP Image

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE_URL:
        description: 'TWRP Device Tree Repository URL'
        required: true
        type: string
      DEVICE_TREE_BRANCH:
        description: 'TWRP Device Tree Branch'
        required: true
        default: 'android-12.1' # Adjust as needed
        type: string
      DEVICE_PATH:
        description: 'Path to the device folder in the tree (e.g., device/xiaomi/redmi_note_8)'
        required: true
        type: string
      DEVICE_NAME:
        description: 'Device Codename (used for lunch command)'
        required: true
        type: string
      TWRP_VERSION:
        description: 'TWRP Version to Build (e.g., 12.1)'
        required: true
        default: '12.1'
        type: string
      BUILD_TARGET:
        description: 'Build Target (usually recoveryimage)'
        required: true
        default: 'recoveryimage'
        type: string

jobs:
  build:
    name: Build TWRP for ${{ inputs.DEVICE_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          sudo apt update
          sudo apt install -y git aria2 wget software-properties-common bc bison build-essential ccache curl flex g++ gcc gettext jq libelf-dev liblz4-tool libncurses5-dev libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools unzip xz-utils zip zlib1g-dev

      - name: Clone TWRP Source
        run: |
          mkdir twrp_source
          cd twrp_source
          git clone --depth=1 https://github.com/TeamWin/android.git -b twrp-${{ inputs.TWRP_VERSION }}
          cd android
          git clone --depth=1 ${{ inputs.DEVICE_TREE_URL }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_PATH }}

      - name: Initialize Build
        run: |
          cd twrp_source/android
          source build/envsetup.sh
          lunch twrp_${{ inputs.DEVICE_NAME }}-eng

      - name: Start Build
        run: |
          cd twrp_source/android
          make clean
          make ${{ inputs.BUILD_TARGET }} -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-image-${{ inputs.DEVICE_NAME }}-${{ github.run_id }}
          path: twrp_source/android/out/target/product/${{ inputs.DEVICE_NAME }}/recovery.img

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: twrp_source/android/out/target/product/${{ inputs.DEVICE_NAME }}/recovery.img
          name: TWRP for ${{ inputs.DEVICE_NAME }} - Build ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Unofficial TWRP build for ${{ inputs.DEVICE_NAME }}
            Device Tree: ${{ inputs.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }}
