name: Automated TWRP Build

on:
  workflow_dispatch:
    inputs:
      DEVICE_MANIFEST_URL:
        description: 'URL to the device-specific manifest file (e.g., device.mk)'
        required: true
        type: string
      BOARD_CONFIG_URL:
        description: 'URL to the BoardConfig.mk file'
        required: true
        type: string
      RECOVERY_FSTAB_URL:
        description: 'URL to the recovery.fstab file'
        required: true
        type: string
      VENDOR_SETUP_URL:
        description: 'URL to the vendorsetup.sh file'
        required: true
        type: string
      DEVICE_CODE_NAME:
        description: 'Device Codename (used for lunch command)'
        required: true
        type: string
      TWRP_VERSION:
        description: 'TWRP Version to Build (e.g., 12.1)'
        required: true
        default: '12.1'
        type: string
      BUILD_TARGET:
        description: 'Build Target (usually recoveryimage)'
        required: true
        default: 'recoveryimage'
        type: string

jobs:
  build:
    name: Build TWRP for ${{ inputs.DEVICE_CODE_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          sudo apt update
          sudo apt install -y git aria2 wget software-properties-common bc bison build-essential ccache curl flex g++ gcc gettext jq libelf-dev liblz4-tool libncurses5-dev libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools unzip xz-utils zip zlib1g-dev

      - name: Create Device Directory
        run: |
          mkdir -p twrp_source/android/device/generic/${{ inputs.DEVICE_CODE_NAME }}

      - name: Download Device Files
        run: |
          cd twrp_source/android/device/generic/${{ inputs.DEVICE_CODE_NAME }}
          wget ${{ inputs.DEVICE_MANIFEST_URL }} -O Android.mk
          wget ${{ inputs.BOARD_CONFIG_URL }} -O BoardConfig.mk
          wget ${{ inputs.RECOVERY_FSTAB_URL }} -O recovery.fstab
          wget ${{ inputs.VENDOR_SETUP_URL }} -O vendorsetup.sh
          chmod +x vendorsetup.sh

      - name: Clone TWRP Source
        run: |
          cd twrp_source
          git clone --depth=1 https://github.com/TeamWin/android.git -b twrp-${{ inputs.TWRP_VERSION }}
          cd android

      - name: Initialize Build
        run: |
          cd twrp_source/android
          source build/envsetup.sh
          lunch twrp_${{ inputs.DEVICE_CODE_NAME }}-eng

      - name: Start Build
        run: |
          cd twrp_source/android
          make clean
          make ${{ inputs.BUILD_TARGET }} -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-image-${{ inputs.DEVICE_CODE_NAME }}-${{ github.run_id }}
          path: twrp_source/android/out/target/product/${{ inputs.DEVICE_CODE_NAME }}/recovery.img

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: twrp_source/android/out/target/product/${{ inputs.DEVICE_CODE_NAME }}/recovery.img
          name: TWRP for ${{ inputs.DEVICE_CODE_NAME }} - Build ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Automated TWRP build for ${{ inputs.DEVICE_CODE_NAME }}
            Device Manifest: ${{ inputs.DEVICE_MANIFEST_URL }}
            BoardConfig: ${{ inputs.BOARD_CONFIG_URL }}
            recovery.fstab: ${{ inputs.RECOVERY_FSTAB_URL }}
            vendorsetup.sh: ${{ inputs.VENDOR_SETUP_URL }}
